import { structureReading } from '../../lib/saju/structure.ts';
import type { SajuChart } from '../../lib/saju/engine.ts';

export default function SajuStructure({chart}:{chart:SajuChart}){
  const data=structureReading(chart);if(!data)return null;
  const {strength,climate,seasonElements,command,common}=data;
  return <section className="sj-structure" aria-label="균형과 보완 방향">
    <div className="sj-structure-heading"><span className="sj-eyebrow">균형을 읽는 세 가지 단서</span><h3>무엇이 나를 받치고,<br/>어디로 힘을 쓰는가.</h3><p>글자 수에 자리와 계절을 더해, 서로 다른 관점에서 살펴봅니다.</p></div>
    <div className="sj-structure-grid">
      <article><span className="sj-eyebrow">01 · 일간 강약 관점</span><h4>{strength?strength.label:'출생 시간 확인 뒤 판단'}</h4>{strength?<><div className="sj-support-value"><b>{strength.score}<small>%</small></b><span>일간을 돕는 기운의 가중 비중</span></div><p>같은 {chart.dayElement} 기운과 일간을 생하는 {strength.supportElement} 기운을 합친 비중입니다. 나머지는 표현·자원 관리·책임으로 힘을 쓰는 역할입니다.</p><p>{strength.candidates.length?`이 관점의 보완 후보는 ${strength.candidates.join('·')}입니다. ${strength.level.includes('strong')?'받치는 힘을 결과로 이어가는 식상 역할을 먼저 살핍니다.':'배움과 협력으로 기반을 받치는 인성·비겁 역할을 먼저 살핍니다.'}`:'이 관점에서는 하나의 보완 오행을 고르지 않습니다. 계절과 월지의 역할을 함께 살핍니다.'}</p><details><summary>자리별 근거와 가중치</summary><div><table><caption>일간 자신을 제외한 일곱 자리 · 합계 가중치 9.5</caption><thead><tr><th>기둥</th><th>천간 / 지지 가중치</th><th>지지의 도움 비중</th></tr></thead><tbody>{strength.rows.map(r=><tr key={r.key}><th>{r.label}</th><td>{r.stemWeight} / {r.branchWeight}</td><td>{Math.round(r.branchRatio*100)}%</td></tr>)}</tbody></table><p>월지 3, 일지 1.5, 다른 지지와 천간은 1로 계산합니다. 지지는 fortuneteller의 절기 세력표 비율로 나눕니다. 이 표는 전월의 잔여 기운도 포함하여 만세력의 지장간 표와 범위가 다릅니다.</p><p>22·35·44·58% 경계는 원본 모델의 구분값입니다. 비중은 운세 점수나 성공 확률이 아니며, 합화·종격·절입 뒤 사령 변화를 모두 반영한 최종 강약 판정은 아닙니다.</p></div></details></>:<p>시주를 임의로 채우지 않아 강약 비중과 보완 후보를 계산하지 않았습니다. 월지와 확인된 지장간의 구성은 아래에서 볼 수 있습니다.</p>}</article>
      <article><span className="sj-eyebrow">02 · 계절 조절 관점</span><h4>{climate.name}의 {climate.elements.join('·')} 기운</h4><p>{data.command!.branch}월은 {climate.condition}입니다. {climate.meaning}으로 읽습니다.</p><ul>{seasonElements.map(e=><li key={e.element}><b>{e.element}</b><span>겉글자 {e.visible}개 · 지장간 {e.hidden.length?e.hidden.join('·'):'없음'}</span></li>)}</ul><p>{common.length?`강약과 계절 관점에서 ${common.join('·')} 후보가 겹칩니다. 어떤 자리에 있고 어떻게 쓰이는지를 우선 살펴볼 단서입니다.`:strength?.candidates.length?'강약과 계절 관점의 후보가 다릅니다. 어느 한쪽만으로 용신을 확정하지 않고 두 조건을 함께 봅니다.':'계절 관점의 후보입니다. 해당 오행이 적다고 무조건 더하거나, 많다고 나쁜 기운으로 정하지 않습니다.'}</p><details><summary>조후란 무엇인가요?</summary><div><p>조후는 절기월의 한난조습, 즉 차가움·따뜻함·마름·습함을 조절하는 명리 관점입니다. 여기서는 원본의 월지별 표를 사용한 기초 비교이며, 출생지의 실제 날씨나 건강 상태를 뜻하지 않습니다.</p><p>일간별 세부 조후, 합화 조건까지 따져 확정한 용신은 아닙니다.</p></div></details></article>
      <article><span className="sj-eyebrow">03 · 월령과 투출</span><h4>{command!.title}</h4>{command!.partial&&<p>시간 미상 · 확인된 세 기둥 기준의 임시 해석입니다.</p>}<p>{command!.month} 월주의 지장간 중 {command!.selected}를 중심으로 읽습니다. 일간과의 십성은 {command!.god}이며, {command!.meaning}입니다.</p><p>{command!.positions.length?`${command!.selected}가 ${command!.positions.join('·')} 천간에도 나타납니다. 안에 담긴 역할이 겉으로도 드러나는 구성이며 이를 투출이라고 합니다.`:`확인된 연간·월간${chart.input.unknownTime?'':'·시간'}에 월지 지장간의 투출은 없습니다. 월지의 중심 글자인 정기를 기준으로 읽었습니다.`}</p><div className="sj-structure-action">{command!.action}</div><details><summary>선택 기준 보기</summary><div><p>월지 지장간을 정기→중기→여기 순서로 보고, 연간·월간·시간에 드러난 첫 글자를 선택합니다. 일간 자체는 투출에 넣지 않습니다. 없으면 정기를 선택합니다.</p><p>{command!.partial?'시간 미상으로 시주의 투출은 확인하지 못해 임시로 읽습니다.':'확인된 네 기둥을 기준으로 읽었습니다.'} 이 결과는 월령격을 살피는 기초 단서이며, 성격·적성이나 특수 격국을 확정하는 분류가 아닙니다.</p></div></details></article>
    </div>
  </section>;
}
